/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnRouteImport } from './routes/en'
import { Route as EngRouteImport } from './routes/eng'
import { Route as AidSlugRouteImport } from './routes/aid.$slug'
import { Route as EnAidSlugRouteImport } from './routes/en_.aid.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EngRoute = EngRouteImport.update({
  id: '/eng',
  path: '/eng',
  getParentRoute: () => rootRouteImport,
} as any)
const AidSlugRoute = AidSlugRouteImport.update({
  id: '/aid/$slug',
  path: '/aid/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAidSlugRoute = EnAidSlugRouteImport.update({
  id: '/en_/aid/$slug',
  path: '/en/aid/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/aid/$slug': typeof AidSlugRoute
  '/en/aid/$slug': typeof EnAidSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/aid/$slug': typeof AidSlugRoute
  '/en/aid/$slug': typeof EnAidSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/aid/$slug': typeof AidSlugRoute
  '/en_/aid/$slug': typeof EnAidSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/eng' | '/aid/$slug' | '/en/aid/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/eng' | '/aid/$slug' | '/en/aid/$slug'
  id: '__root__' | '/' | '/en' | '/eng' | '/aid/$slug' | '/en_/aid/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  EngRoute: typeof EngRoute
  AidSlugRoute: typeof AidSlugRoute
  EnAidSlugRoute: typeof EnAidSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eng': {
      id: '/eng'
      path: '/eng'
      fullPath: '/eng'
      preLoaderRoute: typeof EngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid/$slug': {
      id: '/aid/$slug'
      path: '/aid/$slug'
      fullPath: '/aid/$slug'
      preLoaderRoute: typeof AidSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/aid/$slug': {
      id: '/en_/aid/$slug'
      path: '/en/aid/$slug'
      fullPath: '/en/aid/$slug'
      preLoaderRoute: typeof EnAidSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  EngRoute: EngRoute,
  AidSlugRoute: AidSlugRoute,
  EnAidSlugRoute: EnAidSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
