/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnRouteImport } from './routes/en'
import { Route as EngRouteImport } from './routes/eng'
import { Route as NapryamkySlugRouteImport } from './routes/napryamky.$slug'
import { Route as EnNapryamkySlugRouteImport } from './routes/en_.napryamky.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EngRoute = EngRouteImport.update({
  id: '/eng',
  path: '/eng',
  getParentRoute: () => rootRouteImport,
} as any)
const NapryamkySlugRoute = NapryamkySlugRouteImport.update({
  id: '/napryamky/$slug',
  path: '/napryamky/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNapryamkySlugRoute = EnNapryamkySlugRouteImport.update({
  id: '/en_/napryamky/$slug',
  path: '/en/napryamky/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/napryamky/$slug': typeof NapryamkySlugRoute
  '/en/napryamky/$slug': typeof EnNapryamkySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/napryamky/$slug': typeof NapryamkySlugRoute
  '/en/napryamky/$slug': typeof EnNapryamkySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/eng': typeof EngRoute
  '/napryamky/$slug': typeof NapryamkySlugRoute
  '/en_/napryamky/$slug': typeof EnNapryamkySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/eng' | '/napryamky/$slug' | '/en/napryamky/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/eng' | '/napryamky/$slug' | '/en/napryamky/$slug'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/eng'
    | '/napryamky/$slug'
    | '/en_/napryamky/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  EngRoute: typeof EngRoute
  NapryamkySlugRoute: typeof NapryamkySlugRoute
  EnNapryamkySlugRoute: typeof EnNapryamkySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eng': {
      id: '/eng'
      path: '/eng'
      fullPath: '/eng'
      preLoaderRoute: typeof EngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napryamky/$slug': {
      id: '/napryamky/$slug'
      path: '/napryamky/$slug'
      fullPath: '/napryamky/$slug'
      preLoaderRoute: typeof NapryamkySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/napryamky/$slug': {
      id: '/en_/napryamky/$slug'
      path: '/en/napryamky/$slug'
      fullPath: '/en/napryamky/$slug'
      preLoaderRoute: typeof EnNapryamkySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  EngRoute: EngRoute,
  NapryamkySlugRoute: NapryamkySlugRoute,
  EnNapryamkySlugRoute: EnNapryamkySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
